admin panel changes with User Roles
pinak-globallogic/entrust-license-poc pull request #16
Opened 2022-07-06 07:42 UTC by suraj0001

2022-07-06 10:30 UTC, pinak-globallogic requested changes

2022-07-06 10:30 UTC, pinak-globallogic commented on src/Pages/Admin/UserRoles.jsx
> +      renderHeader: () => <strong>{"License Tool Admin"}</strong>,
String can be used without curly braces

2022-07-06 10:30 UTC, pinak-globallogic commented on src/Pages/Admin/UserRoles.jsx
> +        console.log(err);
remove log

2022-07-06 11:07 UTC, suraj0001 commented on src/Layouts/Nav/AdminNav.jsx
> +          <ListItemButton sx={{ pl: 4 }}>
removing sx and using pl as prop, creating another submenu. So have to use it.

2022-07-07 07:28 UTC, pinak-globallogic approved these changes

2022-07-07 07:28 UTC, merged