Activate Key Changes
pinak-globallogic/entrust-license-poc pull request #19
Opened 2022-07-07 10:48 UTC by Sakshi-gupta-GL

2022-07-08 12:22 UTC, pinak-globallogic requested changes

2022-07-08 12:22 UTC, pinak-globallogic commented on src/Pages/Key/Activate/ActivateKey.jsx
> +const ActivateKey = (props) => {
Refactor it. Create a folder named 'Activate' inside License folder

2022-07-08 12:22 UTC, pinak-globallogic commented on src/Pages/Key/Activate/ActivateKey.jsx
> +const ActivateKey = (props) => {
rename to ActivateLicenseWizard

2022-07-08 12:22 UTC, pinak-globallogic commented on src/Routes/index.jsx
> +export const ACTIVATE_KEY_ROUTE = "/key/activate";
/license/activate

2022-07-11 09:41 UTC, Sakshi-gupta-GL commented on src/Pages/Key/Activate/ActivateKey.jsx
> +const ActivateKey = (props) => {
done

2022-07-11 09:42 UTC, Sakshi-gupta-GL commented on src/Routes/index.jsx
> +export const ACTIVATE_KEY_ROUTE = "/key/activate";
done

2022-07-11 12:14 UTC, pinak-globallogic approved these changes

2022-07-11 12:14 UTC, merged