Added Expiration date page UI
pinak-globallogic/entrust-license-poc pull request #4
Opened 2022-06-30 06:22 UTC by surabhishukla

2022-06-30 09:19 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const [radioValue, setRadioValue] = useState("No expiry Date");
done

2022-06-30 09:20 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +    console.log(e.target.value);
done

2022-06-30 09:20 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +                        ...state,
done

2022-06-30 09:20 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +                    ...state,
done

2022-06-30 09:20 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +import { AppContext } from "./../../../App";
done

2022-06-30 10:43 UTC, pinak-globallogic requested changes

2022-06-30 10:43 UTC, pinak-globallogic commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const EXPIRYDAYS = "Expiry in days:";
Put constants outside of component

2022-06-30 10:43 UTC, pinak-globallogic commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const limitCountValue = (e) => {
onLimitCountChange

2022-06-30 10:43 UTC, pinak-globallogic commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const expirationValue = (e) => {
onExpirationChange

2022-06-30 11:08 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const expirationValue = (e) => {
done

2022-06-30 11:08 UTC, surabhishukla commented on src/Pages/License/Generate/LimitationDetails.jsx
> +  const limitCountValue = (e) => {
done

2022-07-01 06:56 UTC, pinak-globallogic approved these changes

2022-07-01 06:56 UTC, merged